import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

export function getTechIcon(tech: string): string | null {
	const t = tech.toLowerCase();
	const mapping: Record<string, string> = {

		// Backend
		go: "simple-icons:go",
		rust: "simple-icons:rust",
		"node.js": "simple-icons:nodedotjs",
		react: "simple-icons:react",
		"tailwind css": "simple-icons:tailwindcss",
		"next.js": "simple-icons:nextdotjs",
		redis: "simple-icons:redis",
		postgresql: "simple-icons:postgresql",
		websockets: "simple-icons:socketdotio",
		graphql: "simple-icons:graphql",
		"nats.io": "simple-icons:natsdotio",
		"framer motion": "simple-icons:framer",
		figma: "simple-icons:figma",

		// AdonisJS,
		// Amazon SQS,
		// Apache,
		// Apache Kafka,
		// Appwrite,
		// Astro (for content-focused backends via server islands),
		// Auth.js / NextAuth.js,
		// AWS Lambda,
		// Axios,
		// Back4app,
		// Backendless,
		betterauth: "simple-icons:betterauth",
		bun: "simple-icons:bun",
		clerk: "simple-icons:clerk",
		// Cloudflare Workers (serverless edge functions),
		deno: "simple-icons:deno",
		drizzle: "simple-icons:drizzle",
		// Elysia.js (Bun-optimized, type-safe),
		express: "simple-icons:express",
		fastapi: "simple-icons:fastapi",
		fastify: "simple-icons:fastify",
		// Firebase,
		hono: "simple-icons:hono",
		jwt: "simple-icons:jsonwebtokens",
		// Memcached,
		mongodb: "simple-icons:mongodb",
		mongoose: "simple-icons:mongoose",
		mysql: "simple-icons:mysql",
		neon: "simple-icons:neon",
		nginx: "simple-icons:nginx",
		// oauth,
		"openid connect": "simple-icons:openid",
		// PlanetScale,
		pnpm: "simple-icons:pnpm",
		// PostHog,
		prisma: "simple-icons:prisma",
		// RabbitMQ,
		// Remix (full-stack, supports multiple runtimes),
		// Serverless (AWS Lambda, Azure Functions, etc.),
		// Snowflake,
		// Socket.IO,
		sqlite: "simple-icons:sqlite",
		// SvelteKit (with Node.js, Deno, or edge adapters),
		trpc: "simple-icons:trpc",
		// Turso (SQLite at the edge),
		// TypeORM,
		typescript: "simple-icons:typescript",
		// Upstash Redis (serverless Redis with REST),
		// websockets,
		// WorkOS,
		// Vitest,
		// zod,

		// -----------------------------------------------------------------------------------------------------------------

		// DevOps
		docker: "simple-icons:docker",
		kubernetes: "simple-icons:kubernetes",
		terraform: "simple-icons:terraform",
		"github actions": "simple-icons:githubactions",
		aws: "simple-icons:amazonaws",

		alloy: "simple-icons:bun",
		ansible: "simple-icons:bun",
		// Aqua Security,
		"argo cd": "simple-icons:bun",
		// AWS CloudFormation,
		// AWS Secrets Manager,
		// Backstage,
		// BrowserStack,
		// Calico,
		// Cilium,
		// CircleCI,
		// Chef,
		// CodeRabbit,
		// Consul,
		// Datadog,
		// Drone,
		"flux cd": "simple-icons:bun",
		github: "simple-icons:bun",
		gitlab: "simple-icons:bun",
		"gitlab cicd": "simple-icons:bun",
		grafana: "simple-icons:bun",
		// Harbor,
		"hashicorp vault": "simple-icons:bun",
		helm: "simple-icons:bun",
		// Humanitec,
		// Istio,
		// Jenkins,
		// JFrog Artifactory,
		k3d: "simple-icons:bun",
		// Linkerd,
		loki: "simple-icons:bun",
		// OpenPolicy Agent (OPA),
		// OpenTofu,
		// Port,
		prometheus: "simple-icons:bun",
		// Pulumi,
		// Puppet,
		// Qovery,
		// Snyk,
		// SonarQube ,
		// Sonatype Nexus,
		spacelift: "simple-icons:bun",
		// Travis CI,
		// Trivy,
		vercel: "simple-icons:bun",

		// -----------------------------------------------------------------------------------------------------------------

		// Machine Leaarning
		python: "simple-icons:python",
		numpy: "simple-icons:numpy",
		pandas: "simple-icons:pandas",
		seaborn: "devicon-plain:seaborn",
		opencv: "simple-icons:opencv",
		jupyter: "simple-icons:jupyter",
		pytorch: "simple-icons:pytorch",
		tensorflow: "simple-icons:tensorflow",
		matplotlib: "devicon-plain:matplotlib",
		"scikit-learn": "simple-icons:scikitlearn",

		"apache airflow": "simple-icons:apacheairflow",
		bentoml: "simple-icons:bentoml",
		// BigQuery,
		// ClearML,
		// Comet ML,
		// Databricks,
		// Delta Lake,
		"dvc": "simple-icons:dvc",
		// // Flyte,
		"google colab": "simple-icons:googlecolab",
		// // Google Vertex AI,
		"gradio": "simple-icons:gradio",
		// // H2O.ai,
		"hugging face transformers": "simple-icons:huggingface",
		// jax: "simple-icons:jax",
		keras: "simple-icons:keras",
		kubeflow: "devicon-plain:kubeflow",
		// lakefs: "simple-icons:lakefs",
		langchain: "simple-icons:langchain",
		// // llama.cpp,
		// // Metaflow,
		// // Milvus,
		mlflow: "simple-icons:mlflow",
		// // ModelDB,
		// // Neptune.ai,
		"onnx": "simple-icons:onnx",
		ollama: "simple-icons:ollama",
		// // Pinecone,
		// "power bi": "simple-icons:power bi",
		// // Prefect,
		// "pytorch lightning": "simple-icons:pytorch lightning",
		// SageMaker,
		streamlit: "simple-icons:streamlit",
		// // Snowflake,
		"tensorflow extended": "simple-icons:tensorflow",
		// "tensorrt-llm": "simple-icons:tensorrt-llm",
		// torchserve: "simple-icons:torchserve",
		// // TrueFoundry,
		vllm: "simple-icons:vllm",
		// weaviate: "simple-icons:weaviate",
		"weights & biases": "simple-icons:weightsandbiases"
		// ZenML,



	};
	return mapping[t] || null;
}
